### ISSUE TITLE
New Referral Design & Functionality - Responsive

### ISSUE THREAD

**Issue by Navdeepqa** [Navdeepqa/qa#4]
Figma link:- https://www.figma.com/design/pTjEPeVXcBS9nVFCgDJeGj/NEW-DESIGN-SYSTEM---Pages?node-id=8957-1662&node-type=frame&t=xp2397at7bMnGm1B-0

**Comment by VikasQA261** [comment]
1.Screen is not displayed propelry
https://prnt.sc/l2ccqiljD6P4
2.The format of date of birth is incorrect when user enter the DOB manually
https://prnt.sc/rxaCpIlA7kzk
**Fixed**
3.In medicare expiry date field past years is displayed in years and user also able to set past date
https://screenrec.com/share/mkVpLRFgIc
**After client confirmation, i set it from  2024 to 2100** 
4.In private insurance issue date only 4 past years displayed in the years and user is also able to set future dates
https://screenrec.com/share/hsite54BLr

5.In add patient DOB field there is no option to enter the DOB manually
https://prnt.sc/7QWO_iOj-3Xw
**Fixed**
6.In add patient DOB field there is no option to reset
https://prnt.sc/6bBw1PM5qb21
@bilalzafar1 @Rajnishsharma01 
7.Some icons displayed on screen which is i never seen before
https://prnt.sc/hxvgckhC3BzE
**This is not related to website. Check on real device.**
8.user is not able to add the patient when click on "Add" button nothing is happening
https://screenrec.com/share/D1l6LGNeKq
**Fixed**
9.medicare and private insurnace fields are not algined
https://prnt.sc/JJbS1rSCbfop
10.User is not able to unselect the hp by clicking again on selected icon if he want to unselect the hp then he needs to select other hp or click on "x" in seleted hp
https://screenrec.com/share/UAOgmjSiRV
**NAN(No action needed)**
11.imaging and pathlogy request are open but user not getting any validation message when he click on send
https://screenrec.com/share/3yVWE8saeD
**You are not performing any action while updating patient detail. Select either yes or no then you will get the error message.**
12.On confirmation page "Yes" icon is turancated
https://prnt.sc/CZ8VEM79Ag0v
13.When user search the HP by name then getting inapporate validation message
https://prnt.sc/8NHb4CC4Zdpx
**This is as per client requirement and even discuss in the Sunday meeting.**

**Comment by VikasQA261** [comment]
14.When user click on sent then screen is not displayed proplery
https://prnt.sc/FTy5JmyKETdT
**Clear cache**
15.User is not getting relevant result according to search term
https://screenrec.com/share/sWqBZyejR3
**Check other information of patient. This string can be occur in address as well**
16.There is no load more button if there is multiple search result
https://screenrec.com/share/aDepBIsYXJ
**Fine for now. But we will add** 
17.When user search with numbers then the result is not accurate
https://screenrec.com/share/3u0STNvU7e
**Check other information of patient. This string can be occur in other places as well**
18.When user entered the unnecessary spaces then results are displayed 
https://screenrec.com/share/udwJEt23eR
19.When user enter the specail character in the search field then no error message displayed
https://screenrec.com/share/KZiDUGC07O
**Because search start if user enter min 3 characters**
20.Search term is removed but "0 Result" message still displayed
https://prnt.sc/67Nup8U3JYmg
**Please add video**

**Comment by VikasQA261** [comment]
Tested on Tablet mode> Resolution 1280*720(dpi 240)
21.There is no option to leave the MP
https://screenrec.com/share/1C9vp7GlcK
22.In add patient DOB picker there is no option to select the years and month
https://screenrec.com/share/ZPEArKwyNt
23.In step 3 displayed consult notes but in validation message displayed clinical notes
https://screenrec.com/share/Le6sy3IVKr
24.When user edit the draft and send referral then double tick not displayed in sent section
https://screenrec.com/share/5cEdwC7tHr
25.In HP specailty filters selcted filter overlap with tick
https://img001.prntscr.com/file/img001/7aWcKQUmSSCN50tx8VaBtw.png
26.In sent section displayed two load more button
https://screenrec.com/share/csnXUzxQda
27.In sent section when user search with start date and end date then not getting accurate result
https://screenrec.com/share/jCl4OzV8W3
28.When user select the existing patient and update the details that time validation message is not displayed on DOB field also when user click on save button then page not jump 
to the DOB field
https://screenrec.com/share/n7XvUVyAku
29.When user update the existing patient DOB manually and send referrel then in sent section displayed wrong date
https://screenrec.com/share/eLbuWMaz4r
30.User is able to save the draft without fill any field in step 3
https://screenrec.com/share/zownuATEgf
